# Default values, no need to touch
ip_url = u'http://httpbin.org/ip'
manta_base_url = u'https://www.manta.com/'

# Your timezone
timezone = u'US/Pacific'

# Log time format
log_time_format = u'%Y-%m-%d %H:%M:%S %Z'

# Base request headers
base_headers = {
    u'Accept-Encoding': u'gzip, deflate, br',
    u'Accept-Language': u'en-US,en;q=0.5',
    u'Connection': u'keep-alive',
    u'DNT': u'1',
    u'User-Agent': u'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/61.0'
}

# Fill in proxies !!!
proxies = {
    u'http': u'80.211.189.165:3128',
    u'https': u'80.211.189.165:3128',
}

# Do Not Modify This !!!
p = {
    u'proof': None,
    u'fp2': {
        u'userAgent': base_headers[u'User-Agent'].replace(u' ', u''),
        u'language': u'en-US',
        u'screen': {
            u'width': 1920,
            u'height': 1080,
            u'availHeight': 1080,
            u'availWidth': 1920,
            u'innerHeight': 153,
            u'innerWidth': 946,
            u'outerHeight': 1080,
            u'outerWidth': 960,
        },
        u'timezone': -7,
        u'indexedDb': True,
        u'addBehavior': False,
        u'openDatabase': False,
        u'cpuClass': u'unknown',
        u'platform': u'Win64',
        u'doNotTrack': u'1',
        u'plugins': u'',
        u'canvas': {
            u'winding': u'yes',
            u'towebp': False,
            u'blending': True,
            u'img': u'f3e43272d1982de39836aec91c6ade5087bd073d',
        },
        u'webGL': {
            u'img': u'8d37e15cc9363584537e76e4d202a7e8e811da59',
            u'extensions': u'ANGLE_instanced_arrays;EXT_blend_minmax;EXT_color_buffer_half_float;EXT_frag_depth;EXT_sRGB;EXT_shader_texture_lod;EXT_texture_filter_anisotropic;OES_element_index_uint;OES_standard_derivatives;OES_texture_float;OES_texture_float_linear;OES_texture_half_float;OES_texture_half_float_linear;OES_vertex_array_object;WEBGL_color_buffer_float;WEBGL_compressed_texture_s3tc;WEBGL_compressed_texture_s3tc_srgb;WEBGL_debug_renderer_info;WEBGL_debug_shaders;WEBGL_depth_texture;WEBGL_draw_buffers;WEBGL_lose_context',
            u'aliasedlinewidthrange': u'[1,1]',
            u'aliasedpointsizerange': u'[1,1024]',
            u'alphabits': 8,
            u'antialiasing': u'yes',
            u'bluebits': 8,
            u'depthbits': 24,
            u'greenbits': 8,
            u'maxanisotropy': 16,
            u'maxcombinedtextureimageunits': 32,
            u'maxcubemaptexturesize': 16384,
            u'maxfragmentuniformvectors': 1024,
            u'maxrenderbuffersize': 16384,
            u'maxtextureimageunits': 16,
            u'maxtexturesize': 16384,
            u'maxvaryingvectors': 30,
            u'maxvertexattribs': 16,
            u'maxvertextextureimageunits': 16,
            u'maxvertexuniformvectors': 4096,
            u'maxviewportdims': u'[32767,32767]',
            u'redbits': 8,
            u'renderer': u'Mozilla',
            u'shadinglanguageversion': u'WebGLGLSLES1.0',
            u'stencilbits': 0,
            u'vendor': u'Mozilla',
            u'version': u'WebGL1.0',
            u'vertexshaderhighfloatprecision': 23,
            u'vertexshaderhighfloatprecisionrangeMin': 127,
            u'vertexshaderhighfloatprecisionrangeMax': 127,
            u'vertexshadermediumfloatprecision': 23,
            u'vertexshadermediumfloatprecisionrangeMin': 127,
            u'vertexshadermediumfloatprecisionrangeMax': 127,
            u'vertexshaderlowfloatprecision': 23,
            u'vertexshaderlowfloatprecisionrangeMin': 127,
            u'vertexshaderlowfloatprecisionrangeMax': 127,
            u'fragmentshaderhighfloatprecision': 23,
            u'fragmentshaderhighfloatprecisionrangeMin': 127,
            u'fragmentshaderhighfloatprecisionrangeMax': 127,
            u'fragmentshadermediumfloatprecision': 23,
            u'fragmentshadermediumfloatprecisionrangeMin': 127,
            u'fragmentshadermediumfloatprecisionrangeMax': 127,
            u'fragmentshaderlowfloatprecision': 23,
            u'fragmentshaderlowfloatprecisionrangeMin': 127,
            u'fragmentshaderlowfloatprecisionrangeMax': 127,
            u'vertexshaderhighintprecision': 0,
            u'vertexshaderhighintprecisionrangeMin': 31,
            u'vertexshaderhighintprecisionrangeMax': 30,
            u'vertexshadermediumintprecision': 0,
            u'vertexshadermediumintprecisionrangeMin': 31,
            u'vertexshadermediumintprecisionrangeMax': 30,
            u'vertexshaderlowintprecision': 0,
            u'vertexshaderlowintprecisionrangeMin': 31,
            u'vertexshaderlowintprecisionrangeMax': 30,
            u'fragmentshaderhighintprecision': 0,
            u'fragmentshaderhighintprecisionrangeMin': 31,
            u'fragmentshaderhighintprecisionrangeMax': 30,
            u'fragmentshadermediumintprecision': 0,
            u'fragmentshadermediumintprecisionrangeMin': 31,
            u'fragmentshadermediumintprecisionrangeMax': 30,
            u'fragmentshaderlowintprecision': 0,
            u'fragmentshaderlowintprecisionrangeMin': 31,
            u'fragmentshaderlowintprecisionrangeMax': 30,
        },
        u'touch': {
            u'maxTouchPoints': 0,
            u'touchEvent': False,
            u'touchStart': False,
        },
        u'video': {
            u'ogg': u'probably',
            u'h264': u'probably',
            u'webm': u'probably',
        },
        u'audio': {
            u'ogg': u'probably',
            u'mp3': u'maybe',
            u'wav': u'probably',
            u'm4a': u'maybe',
        },
        u'vendor': u'',
        u'product': u'Gecko',
        u'productSub': u'20100101',
        u'browser': {
            u'ie': False,
            u'chrome': False,
            u'webdriver': False
        },
        u'fonts': u'Batang;Calibri;Century;Clarendon;EUROSTILE;GillSans;Haettenschweiler;Leelawadee;Marlett;PMingLiU;Pristina;SimHei;Vrinda',
    },
    u'cookies': 1,
    u'setTimeout': 0,
    u'setInterval': 0,
    u'appName': u'Netscape',
    u'platform': u'Win64',
    u'syslang': u'en-US',
    u'userlang': u'en-US',
    u'cpu': u'WindowsNT6.1;Win64;x64',
    u'productSub': u'20100101',
    u'plugins': {},
    u'mimeTypes': {},
    u'screen': {
        u'width': 1920,
        u'height': 1080,
        u'colorDepth': 24,
    },
    u'fonts': {
        u'0': u'Calibri',
        u'1': u'Cambria',
        u'2': u'HoeflerText',
        u'3': u'Monaco',
        u'4': u'Constantia',
        u'5': u'LucidaBright',
        u'6': u'Georgia',
        u'7': u'SegoeUI',
        u'8': u'Candara',
        u'9': u'TrebuchetMS',
        u'10': u'Verdana',
        u'11': u'Consolas',
        u'12': u'LucidaConsole',
        u'13': u'LucidaSansTypewriter',
        u'14': u'Monaco',
        u'15': u'CourierNew',
        u'16': u'Courier',
    },
}
